mod 'boxen', '3.7.0.beta1', :github_tarball => 'boxen/puppet-boxen'
mod "module-data", "0.0.4", :github_tarball => "ripienaar/puppet-module-data"
mod 'stdlib', '4.3.2', :github_tarball => "puppetlabs/puppetlabs-stdlib"
